### ISSUE TITLE
GPS logging not inline when no fix

### ISSUE THREAD

**Issue by Hailyk** [mydogisjibe/NewMagnitudeAlphaShield#6]
when GPS has no fix the logging of the GPS data is not in line.
`No GPS Fix
GPS: Invalid Lat
GPS: Invalid Long
GPS: Invalid Alt
GPS: Invalid Speed
th02Temp: 21.48,humidity: 60.54,bmp180Temp: 22.14,pressure: 1013.22,Altitude0.73accel_x: 0.98,accel_y: 0.02,accel_z: 0.11,mag_x: 6.50,mag_y: -9.65,mag_z: -1.52,gps_lat: 0.000000,gps_lon: 0.000000,gps_alt: 0.00,gps_speed(mps): 0.00
No GPS Fix
GPS: Invalid Lat
GPS: Invalid Long
GPS: Invalid Alt
GPS: Invalid Speed
th02Temp: 21.50,humidity: 60.54,bmp180Temp: 22.13,pressure: 1013.22,Altitude0.76accel_x: 0.98,accel_y: 0.02,accel_z: 0.11,mag_x: 6.49,mag_y: -9.67,mag_z: -1.52,gps_lat: 0.000000,gps_lon: 0.000000,gps_alt: 0.00,gps_speed(mps): 0.00
`

**Comment by NSagan271** [comment]
`**No GPS Fix****GPS: Invalid Lat****GPS: Invalid Lon****GPS: Invalid Alt****GPS: Invalid Speed**th02Temp: 24.31,humidity: 45.67,bmp180Temp: 25.11,pressure: 1012.61,Altitude-0.64accel_x: 0.14,accel_y: 0.02,accel_z: 0.95,mag_x: 1.79,mag_y: -1.09,mag_z: -4.09,gps_lat: 0.000000,gps_lon: 0.000000,gps_alt: 0.00,gps_speed(mps): 0.00,Date: 0,Time: 4294967295
**No GPS Fix****GPS: Invalid Lat****GPS: Invalid Lon****GPS: Invalid Alt****GPS: Invalid Speed**th02Temp: 24.31,humidity: 45.67,bmp180Temp: 25.12,pressure: 1012.64,Altitude-0.86accel_x: 0.15,accel_y: 0.02,accel_z: 0.96,mag_x: 1.78,mag_y: -1.08,mag_z: -4.08,gps_lat: 0.000000,gps_lon: 0.000000,gps_alt: 0.00,gps_speed(mps): 0.00,Date: 0,Time: 4294967295
`
Is this OK?

**Comment by Hailyk** [comment]
@NSagan271 looks good, wanted to take one line so it is easier to read.
